### PR TITLE
Inet framework/master

### PR DESCRIPTION
**Pull request by aarizaq**
This is an adaptation to the latest inet-framework code for omnet 6-pre9

### CODE REVIEW

**Comment by wischhof** [comment]
Hi Alfonso, this is great - thanks for the pull request! 

Which inet branch do we need to use? Using the Tag v4.2.1 as recommended for omnet 6-pre9, the getTagForUpdate and more are still not found.

**Comment by aarizaq** [comment]
https://github.com/inet-framework/inet
master branch, it is the latest code revision. 

The config file must be removed from the network definition and set in the omnetpp.ini file. In other case, the xml file must be in the same directory than the network.
I have commented the parameter.

**Comment by wischhof** [comment]
Ok, thanks for the info! Yes, with the current master it works and I think, we should, of course, merge the changes. However, since the INET master is a "moving target" I would suggest not to merge right now but to wait until a tagged INET version is available - as far as I now, INET 4.3 will be available soon. Then we can simply state that our simulte fork requires INET v4.3. Ok?

**Comment by aarizaq** [comment]
yes, it is for inet 4.3

**Comment by aarizaq** [comment]
I think that it is necessary to create a branch of simulte for inet-4.3

**Comment by wischhof** [comment]
Yes, I think you are right. I created a new branch "inet_4_3_update" and pulled your changes in:
[https://github.com/roVer-HM/simulte/tree/inet_4_3_update](https://github.com/roVer-HM/simulte/tree/inet_4_3_update)

 Then I corrected the failing test-cases (mainly due to a new behavior of the LteNetworkConfigurator). I would suggest to work on this separate branch until inet 4.3 is available and omnet 6.0 is released, then we can merge the update to the master.

**Comment by wischhof** [comment]
Has already been merged via #3

**Pull request closed without merging**
